site_name: Hitchhiker's Guide
locale: en
site_url: https://thomaskokholm.github.io/guide
repo_url: https://github.com/thomaskokholm/guide/
theme:
  name: material
docs_dirïƒ: Guide
extra_css:
  - css/extra.css
